language: rust
sudo: required
os:
- linux
rust:
- stable
services:
- docker
before_install:
- chmod +x build.sh
before_deploy: "./build.sh torchbear ${TRAVIS_OS_NAME}"
deploy:
  provider: releases
  api_key:
    secure: joYKMGm3LRrPPlXGaQlgmWG26zU+70cBGzq+BPJtI4m6mNp51113pD/d0C3Fg9EzwemkApUQn9uZ7wQ8dvFgfGjqDBP6kA2LdTEV9L7P51YqaHp4VK5O6xuKMQuJwB1EVS5NB43YAK2Qax7f2Wkjg3Xmvc8GoJYCyF9yjRAWH8zdyBRibQq8q1dZCynXhnWBIMuJucHGojHTaehIPGQ+oi3pSWukGoWZ3gpBbDDlMmz9vS1Bp63yBtk8ITCgcJP98eRfnduG5hTuwxXprFgTxjJEN1QExqiF/gqld92P5zejsz5TMxf9Ks0r9VinWwWss/3NmhVPhWwoqfS5KT3RREXjG0k7/eorgt5HflyE6gXCDHfPVbJIVCFhJp8qnlSg8WHibw9yk66c4p5xrRnedhSJIGRwHeYfFUtJof+tmV9fNv6iOI1y+xi9qbFvIminU9lh+hbCByPg1owizALl8FZ/KGfEbQZKCEjhN0Xn6ZSUI10J3mOxQKlEBNB0nZwIeDqLJhxDWEeRc9fzybEFTxqupMhwQApVSEnyt19OEPKcxd2etvj1/yw9yPuIa7JDWu7n1jqEXjvOaUE8395vwzuvkGaSaFgQb0oTTUb2JhVd1vvDeDiJ7mb2w9A9WOZ2mFADo4nyq3rHBDhr2gl/dKyeTmbNn6TSOZ8qR+CoNQs=
  file_glob: true
  file: "torchbear-${TRAVIS_OS_NAME}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    rust: stable
  
