language: rust
rust: stable
sudo: required
env:
  global:
  - PROJECT: torchbear
matrix:
  include:
    - os: linux
      rust: stable
      env:
      - ARCH=x86_64
      - PLATFORM=linux
      - CHANNEL=stable
      services: docker
      script: echo "cargo test temporarily disabled"
      before_deploy:
      - docker build -t build-${PROJECT}-image .
      - docker run -it --name build-${PROJECT} build-${PROJECT}-image
      - docker cp build-${PROJECT}:/home/rust/src/target/x86_64-unknown-linux-musl/release/${PROJECT} ${PROJECT}
      - docker rm build-${PROJECT}
      - docker rmi build-${PROJECT}-image
      - wget -O init.lua https://raw.githubusercontent.com/foundpatterns/file-witness/master/sign.lua
      - ./${PROJECT}
      - mkdir ${PROJECT}-bin && mv ${PROJECT} ${PROJECT}-bin/ && mv *.sig ${PROJECT}-bin/
      - zip -r ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}-bin
    - os: linux
      rust: nightly
      env:
      - ARCH=x86_64
      - PLATFORM=linux
      - CHANNEL=nightly
      services: docker
      script: echo "cargo test temporarily disabled"
      before_deploy:
      - docker build -f Dockerfile.nightly -t build-${PROJECT}-image .
      - docker run -it --name build-${PROJECT} build-${PROJECT}-image
      - docker cp build-${PROJECT}:/home/rust/src/target/x86_64-unknown-linux-musl/release/${PROJECT} ${PROJECT}
      - docker rm build-${PROJECT}
      - docker rmi build-${PROJECT}-image
      - wget -O init.lua https://raw.githubusercontent.com/foundpatterns/file-witness/master/sign.lua
      - ./${PROJECT}
      - mkdir ${PROJECT}-bin && mv ${PROJECT} ${PROJECT}-bin/ && mv *.sig ${PROJECT}-bin/
      - zip -r ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}-bin
    - os: osx
      rust: stable
      env:
      - ARCH=x86_64
      - PLATFORM=apple
      - CHANNEL=stable
      script: echo "cargo test temporarily disabled"
      before_deploy:
      - cargo build --release
      - wget -O init.lua https://raw.githubusercontent.com/foundpatterns/file-witness/master/sign.lua
      - ./${PROJECT}
      - mkdir ${PROJECT}-bin && mv ${PROJECT} ${PROJECT}-bin/ && mv *.sig ${PROJECT}-bin/
      - zip -r ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}-bin
    - os: linux
      env:
      - ARCH=arm64
      - PLATFORM=android
      - CHANNEL=stable
      script: echo "cargo test temporarily disabled"
      before_deploy:
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustup target add aarch64-linux-android
      - wget -q https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
      - unzip -qq android-ndk-r18b-linux-x86_64.zip
      - export NDK_HOME="$PWD/android-ndk-r18b"
      - mkdir NDK
      - ${NDK_HOME}/build/tools/make-standalone-toolchain.sh --arch=arm64 --install-dir=NDK/aarch64 --platform=android-22
      - export PATH="$PATH:$PWD/NDK/aarch64/bin"
      - cargo build --target="aarch64-linux-android" --release
      - mv target/aarch64-linux-android/release/${PROJECT} .
      - wget -O init.lua https://raw.githubusercontent.com/foundpatterns/file-witness/master/sign.lua
      - ./${PROJECT}
      - mkdir ${PROJECT}-bin && mv ${PROJECT} ${PROJECT}-bin/ && mv *.sig ${PROJECT}-bin/
      - zip -r ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}-bin
    - os: linux
      env:
      - ARCH=arm32
      - PLATFORM=android
      - CHANNEL=stable
      script: echo "cargo test temporarily disabled"
      before_deploy:
      - export PATH="$HOME/.cargo/bin:$PATH"
      - rustup target add arm-linux-androideabi
      - wget -q https://dl.google.com/android/repository/android-ndk-r18b-linux-x86_64.zip
      - unzip -qq android-ndk-r18b-linux-x86_64.zip
      - export NDK_HOME="$PWD/android-ndk-r18b"
      - mkdir NDK
      - ${NDK_HOME}/build/tools/make-standalone-toolchain.sh --arch=arm --install-dir=NDK/arm --platform=android-22
      - export PATH="$PATH:$PWD/NDK/arm/bin"
      - cargo build --target="arm-linux-androideabi" --release
      - mv target/arm-linux-androideabi/release/${PROJECT} .
      - wget -O init.lua https://raw.githubusercontent.com/foundpatterns/file-witness/master/sign.lua
      - ./${PROJECT}
      - mkdir ${PROJECT}-bin && mv ${PROJECT} ${PROJECT}-bin/ && mv *.sig ${PROJECT}-bin/
      - zip -r ${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.zip ${PROJECT}-bin
before_install:
- openssl aes-256-cbc -K $encrypted_3f0c7a8b3f66_key -iv $encrypted_3f0c7a8b3f66_iv -in private_key.enc -out private_key -d
deploy:
  provider: releases
  api_key:
    secure: CgTP0SwOefwSUsePWKYuZCEV2QNVH3GJcMfComUgBCnPbdrfA8vnC7Ao3Sb31NHZ43k89+DhxCsVtDaWBhmMWqnost5aJ7LGfaEvObL9Cdg06OJv8o9UAcowSqU4k3eHEr0ZRJzEWEiAMTAtclzosmA1PfzyY7MyIv6ZAcoyoUg1uwzr0KJrc/dGN+tkWv/6M1IBgh5kji0yfg9yxjxClJ28GikAJoRmTv+Yx1tQQ+Q/qlkbVT+fVAc0vWwvk/YIauF1s2LBPhMKqkUmmpHyZVk9g3er421ddYjesLt25wMocmtRlWTrEn4G1RVLbQG6+mE+adyw7Oi081CvmJjF4eojsyOYbWI89qJBM0ZAAqzrXNwizZCdL7ShX/I5jHJTA/AMa2GyyLTFbR4CQT/+Otn0nfPLFfiY1g654CFcL73mRnDtixpGMx1aMJ4ScXbMR8rCDDO8hix7pOm71LtCqUAchOYCyNsn4MCkz2+LaH9WZ/hDJDmUgMVVBoqhGLb2vnaf3fd+vbeKFwpLDluFLRrunM+qdNPDPDHzb3qoXcospNnZEt18O3Pu5vMssxIaKEiesm2zTsd/+R4pl4Acotgiy/jLJucFRVs5Id+RpD/eETk/ZnR3Jekpkl6T95w82an1mGS8o8fl/F+CkNBOAn5J8a6gz0nXhjp6APLfErg=
  file_glob: true
  file: "${PROJECT}-${TRAVIS_TAG}-${ARCH}-${PLATFORM}-${CHANNEL}.*"
  skip_cleanup: true
  on:
    repo: foundpatterns/torchbear
    tags: true
branches:
  only:
  - master
  - /.*/
  - /^\d+\.\d+\.\d+.*$/
notifications:
  email:
    on_success: never
